title: Whezit Policies
description: Legal policies and terms for the Whezit bookmark management app
theme: jekyll-theme-cayman

url: "https://www.whiteorcaoptims.com"
baseurl: ""

permalink: pretty

# SEO and social
author: White Orca Optims
lang: en_US
